import type { Metadata } from "next";
import { PRODUCT_NAME } from "@gitspore/shared";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: PRODUCT_NAME,
  description: "A minimal Next.js + React Three Fiber setup",
};

// LayoutProps is a global helper generated by `next dev` / `next build` /
// `next typegen`; it types `children` and any named slots for this route.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
