import type { Metadata } from "next";
import { PRODUCT_NAME } from "@gitspore/shared";
import { Figtree, Fredoka, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

// cozy-06 type (design-docs/design/components.md): Fredoka for logo and titles,
// Figtree for the interface, JetBrains Mono for the terminal.
// globals.css maps these variables to font-title, font-ui / font-sans, font-mono.
const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: PRODUCT_NAME,
  description: "Each AI coding agent as a plant on a greenhouse table",
};

// LayoutProps is a global helper generated by `next dev` / `next build` /
// `next typegen`; it types `children` and any named slots for this route.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fredoka.variable} ${figtree.variable} ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
