// Generates the theme files from the token sources in src/theme:
//   tokens.json      Penpot token sets (cozy-06/base, /shared, /day, /night), dumped from Penpot
//   typography.json  Penpot library typographies
//   scene.json       3D scene values (not in Penpot)
// Outputs: src/theme/tokens.css, src/theme/tailwind.css, src/theme/tokens.ts and
// design-docs/design/tokens.html. `--check` writes nothing and fails if an output is stale.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const here = path.dirname(fileURLToPath(import.meta.url));
const themeDir = path.resolve(here, "../src/theme");
const repoRoot = path.resolve(here, "../../..");
const check = process.argv.includes("--check");

const HEADER =
  "Generated by `npm run tokens` from apps/web/src/theme/*.json. Do not edit.";
const PX_TYPES = new Set([
  "sizing",
  "spacing",
  "borderRadius",
  "borderWidth",
  "dimension",
]);
// Written in rem in CSS (1rem = 16px), except the names in PX_KEEP. tokens.ts keeps px numbers.
const REM_TYPES = new Set(["sizing", "spacing", "borderRadius"]);
const PX_KEEP = new Set([
  "space.focus-offset",
  "space.terminal.screen",
  "size.terminal-min-width",
  "radius.full",
]);
// Content groups: raw values allowed, no Tailwind utilities, interface tokens never point into them.
const CONTENT = /^color\.(agent|art|xterm)\./;
// Tokens outside cozy-06/base that may hold a raw value instead of a reference into base.
const RAW_ALLOWED = [
  CONTENT,
  /^(shadow|border|font)\./,
  /^(size\.panel-width|size\.terminal-min-width|space\.focus-offset)$/,
];
// Base scales: no Tailwind utility (Tailwind's own p-4, w-10, opacity-35 are the same values). Base radii are emitted.
const BASE_SCALE = /^(palette\.|(space|size|opacity)\.\d+$)/;
const ALPHA_STEPS = [0.1, 0.2, 0.35, 0.5];
// Fallbacks after the font named in Penpot. next/font in layout.tsx sets --font-<family>, e.g. --font-fredoka.
const FONT_STACKS = {
  title: '"Figtree", system-ui, sans-serif',
  ui: "system-ui, sans-serif",
  mono: "ui-monospace, monospace",
};
// xterm theme key → key in color.xterm.<light|dark>. The cursor uses fg on bg.
const XTERM_KEYS = {
  background: "bg",
  foreground: "fg",
  cursor: "fg",
  cursorAccent: "bg",
  selectionBackground: "selection",
};
const ANSI = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
];

// ---------- reading

const readJson = async (file) =>
  JSON.parse(await readFile(path.join(themeDir, file), "utf8"));

function flatten(node, prefix = "", out = new Map()) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const name = prefix + key;
    if (value && typeof value === "object" && "$value" in value) {
      out.set(name, { type: value.$type, value: value.$value });
    } else if (value && typeof value === "object") {
      flatten(value, name + ".", out);
    }
  }
  return out;
}

const tokenJson = await readJson("tokens.json");
const sceneJson = await readJson("scene.json");
const typographyJson = await readJson("typography.json");

const sets = {
  base: flatten(tokenJson["cozy-06/base"] ?? {}),
  shared: flatten(tokenJson["cozy-06/shared"]),
  day: flatten(tokenJson["cozy-06/day"]),
  night: flatten(tokenJson["cozy-06/night"]),
};
const sceneSets = {
  shared: flatten(sceneJson["scene/shared"]),
  day: flatten(sceneJson["scene/day"]),
  night: flatten(sceneJson["scene/night"]),
};
const uiEnv = (mode) => new Map([...sets.base, ...sets.shared, ...sets[mode]]);
const fullEnv = (mode) =>
  new Map([...uiEnv(mode), ...sceneSets.shared, ...sceneSets[mode]]);

// ---------- values

const REF = /^\{([^}]+)\}$/;
const refOf = (value) =>
  typeof value === "string" ? value.match(REF)?.[1] : undefined;

function resolve(env, name, seen = []) {
  if (seen.includes(name))
    throw new Error(`Reference cycle: ${[...seen, name].join(" → ")}`);
  const token = env.get(name);
  if (!token)
    throw new Error(
      `Unknown token {${name}}${seen.length ? ` (from ${seen.at(-1)})` : ""}`,
    );
  const ref = refOf(token.value);
  if (ref) return { ...resolve(env, ref, [...seen, name]), type: token.type };
  if (typeof token.value === "string" && token.value.includes("{")) {
    throw new Error(
      `${name}: math in token values is not supported yet (${token.value})`,
    );
  }
  return token;
}

function num(name, value) {
  const n = Number(value);
  if (!Number.isFinite(n))
    throw new Error(`${name}: expected a number, got ${JSON.stringify(value)}`);
  return n;
}

const cssShadow = (list) =>
  list
    .map(
      (s) =>
        `${s.inset ? "inset " : ""}${s.offsetX}px ${s.offsetY}px ${s.blur}px ${s.spread}px ${s.color}`,
    )
    .join(", ");

const fontFace = (family) =>
  `--font-${family.toLowerCase().replaceAll(" ", "-")}`;

const trim = (n, digits = 4) => String(Number(n.toFixed(digits)));
const rem = (px) => `${trim(px / 16)}rem`;
const inRem = (name, type) => REM_TYPES.has(type) && !PX_KEEP.has(name);

// CSS value of a raw (unresolved) token: references stay var() so they follow the mode.
// PX_KEEP names are resolved instead (base and shared are mode-free), so a px token can point at a rem one.
function cssValue(name, token) {
  if (PX_KEEP.has(name)) {
    const t = resolve(uiEnv("day"), name);
    return `${num(name, t.value)}px`;
  }
  const ref = refOf(token.value);
  if (ref) return `var(${cssVar(ref)})`;
  const { type, value } = token;
  if (inRem(name, type)) return rem(num(name, value));
  if (PX_TYPES.has(type)) return `${num(name, value)}px`;
  if (type === "shadow") return cssShadow(value);
  if (type === "fontFamilies") {
    const key = name.split(".").at(-1);
    return `var(${fontFace(value[0])}, "${value[0]}"), ${FONT_STACKS[key] ?? "sans-serif"}`;
  }
  return String(value);
}

// TS value of a resolved token.
function tsValue(name, token) {
  const { type, value } = token;
  if (PX_TYPES.has(type) || type === "opacity" || type === "number")
    return num(name, value);
  if (type === "shadow") return cssShadow(value);
  if (type === "fontFamilies") return value[0];
  return value;
}

const cssVar = (name) => `--${name.replaceAll(".", "-")}`;

// ---------- checks

for (const set of ["shared", "day", "night"]) {
  for (const [name, token] of sets[set]) {
    const ref = refOf(token.value);
    if (!ref && !RAW_ALLOWED.some((re) => re.test(name)))
      throw new Error(
        `${name} (cozy-06/${set}): raw value ${JSON.stringify(token.value)}; point it at a cozy-06/base token`,
      );
    if (ref && CONTENT.test(ref) && !CONTENT.test(name))
      throw new Error(
        `${name} (cozy-06/${set}): interface tokens must not point into content (${ref})`,
      );
  }
}
for (const [name, token] of sets.base) {
  if (!name.startsWith("palette.alpha.")) continue;
  const alpha = String(token.value).match(
    /^rgba\(\s*[\d.]+\s*,\s*[\d.]+\s*,\s*[\d.]+\s*,\s*([\d.]+)\s*\)$/,
  )?.[1];
  if (!ALPHA_STEPS.includes(Number(alpha)))
    throw new Error(
      `${name}: alpha must be one of ${ALPHA_STEPS.join(", ")} (got ${token.value})`,
    );
}

// ---------- typography

const typographies = [];
for (const [group, entries] of Object.entries(typographyJson)) {
  if (group.startsWith("$")) continue;
  for (const [key, t] of Object.entries(entries)) {
    typographies.push({
      group,
      key,
      id: `${group}-${key}`,
      ...t,
      family: refOf(t.fontFamily),
    });
  }
}
// Font sizes in rem, letter spacing in em. mono/terminal stays px, like everything terminal.
const typeSize = (t) =>
  t.id === "mono-terminal" ? `${t.fontSize}px` : rem(t.fontSize);
const typeTracking = (t) => `${trim(t.letterSpacing / t.fontSize, 3)}em`;
const typeVars = (t) => {
  const v = `--text-${t.id}`;
  return [
    [v, typeSize(t)],
    [`${v}--line-height`, String(t.lineHeight)],
    [`${v}--font-weight`, String(t.fontWeight)],
    [`${v}--letter-spacing`, typeTracking(t)],
  ];
};

// ---------- tokens.css

function cssBlock(selector, entries, indent = "") {
  const lines = entries.map(([name, value]) => `${indent}  ${name}: ${value};`);
  return `${indent}${selector} {\n${lines.join("\n")}\n${indent}}`;
}

// --color-terminal-<k> follows the mode (xterm light by day, dark at night) unless a window overrides it.
const terminalKeys = [...sets.shared.keys()]
  .filter((n) => n.startsWith("color.xterm.light."))
  .map((n) => n.slice("color.xterm.light.".length));
const terminal = (pal) =>
  terminalKeys.map((k) => [
    cssVar(`color.terminal.${k}`),
    `var(${cssVar(`color.xterm.${pal}.${k}`)})`,
  ]);

function buildCss() {
  const root = [...sets.base, ...sets.shared, ...sets.day].map(([n, t]) => [
    cssVar(n),
    cssValue(n, t),
  ]);
  root.push(...terminal("light"));
  for (const t of typographies) {
    root.push(...typeVars(t), [
      `--type-${t.id}`,
      `${t.fontWeight} ${typeSize(t)}/${t.lineHeight} var(${cssVar(t.family)})`,
    ]);
  }
  const night = [
    ...[...sets.night].map(([n, t]) => [cssVar(n), cssValue(n, t)]),
    ...terminal("dark"),
  ];
  const caseRules = typographies
    .filter((t) => t.textTransform !== "none")
    .map(
      (t) => `/* ${t.group}/${t.key}: text-transform: ${t.textTransform} */`,
    );

  return [
    `/* ${HEADER} */`,
    "/* Day on :root, night under .dark (next-themes) or the system setting when no theme class is set. */",
    ...caseRules,
    cssBlock(":root", root),
    cssBlock(".dark", night),
    `@media (prefers-color-scheme: dark) {\n${cssBlock(":root:not(.light)", night, "  ")}\n}`,
    "/* Per-window terminal switch: overrides the mode inside one window. */",
    cssBlock(".terminal-light", terminal("light")),
    cssBlock(".terminal-dark", terminal("dark")),
    "",
  ].join("\n\n");
}

// ---------- tailwind.css

// Token group → Tailwind theme namespace. Groups not listed get no utility; use e.g. opacity-(--opacity-disabled).
const TW_NAMESPACE = {
  color: "color",
  radius: "radius",
  shadow: "shadow",
  font: "font",
  size: "spacing",
  space: "spacing",
};
// shadcn already uses bg-muted and bg-accent for its own roles; reach ours through text-muted-foreground and bg-primary.
const TW_SKIP = new Set(["color.muted", "color.accent"]);
// The terminal colours that get a utility (bg-terminal-bg, text-terminal-fg); they are not tokens themselves.
const TW_TERMINAL = ["bg", "fg"];
const twName = (name) => {
  if (TW_SKIP.has(name) || BASE_SCALE.test(name) || CONTENT.test(name))
    return null;
  const [group, ...rest] = name.split(".");
  const ns = TW_NAMESPACE[group];
  if (!ns) return null;
  const tail = rest.join("-");
  return { ns, tail, variable: `--${ns}-${tail}`, renamed: ns !== group };
};

function buildTailwind() {
  const env = uiEnv("day");
  const seen = new Map();
  const lines = ["  --color-*: initial;"];
  const inline = [];
  for (const name of env.keys()) {
    const tw = twName(name);
    if (!tw) continue;
    if (seen.has(tw.variable))
      throw new Error(
        `Tailwind name clash: ${name} and ${seen.get(tw.variable)} → ${tw.variable}`,
      );
    seen.set(tw.variable, name);
    if (tw.renamed || tw.ns === "shadow") {
      // size.* and space.* share Tailwind's spacing namespace, and Tailwind copies shadow values into the
      // utility; inline makes those utilities read the token variable, so they follow the mode.
      inline.push(`  ${tw.variable}: var(${cssVar(name)});`);
    } else {
      // Same name as the CSS variable: `reference` keeps Tailwind from redefining it, utilities use var(--x, day value).
      lines.push(`  ${tw.variable}: ${cssValue(name, resolve(env, name))};`);
    }
  }
  for (const k of TW_TERMINAL) {
    const name = `color.xterm.light.${k}`;
    lines.push(
      `  ${cssVar(`color.terminal.${k}`)}: ${cssValue(name, resolve(env, name))};`,
    );
  }
  for (const t of typographies)
    lines.push(...typeVars(t).map(([n, v]) => `  ${n}: ${v};`));
  return [
    `/* ${HEADER} */`,
    "/* Import after tailwindcss and next to tokens.css, which defines the values per mode. */",
    `@theme reference {\n${lines.join("\n")}\n}`,
    `@theme inline reference {\n${inline.join("\n")}\n}`,
    "",
  ].join("\n\n");
}

// ---------- tokens.ts

function nestInto(target, name, value) {
  const parts = name.split(".");
  let node = target;
  for (const p of parts.slice(0, -1)) node = node[p] ??= {};
  node[parts.at(-1)] = value;
}

function resolvedTree(mode) {
  const env = fullEnv(mode);
  const tree = {};
  for (const name of env.keys())
    nestInto(tree, name, tsValue(name, resolve(env, name)));
  return tree;
}

function xtermTheme(pal) {
  const env = uiEnv("day");
  const get = (k) => tsValue(k, resolve(env, `color.xterm.${pal}.${k}`));
  const theme = {};
  for (const [key, k] of Object.entries(XTERM_KEYS)) theme[key] = get(k);
  for (const c of ANSI) {
    theme[c] = get(`ansi.${c}`);
    theme[`bright${c[0].toUpperCase()}${c.slice(1)}`] = get(`ansi.bright-${c}`);
  }
  return theme;
}

function buildTs() {
  const env = uiEnv("day");
  const typography = {};
  for (const t of typographies) {
    typography[t.group] ??= {};
    typography[t.group][t.key] = {
      fontFamily: tsValue(t.family, resolve(env, t.family)),
      fontSize: t.fontSize,
      fontWeight: t.fontWeight,
      lineHeight: t.lineHeight,
      letterSpacing: t.letterSpacing,
      textTransform: t.textTransform,
    };
  }
  const json = (v) => JSON.stringify(v, null, 2);
  return [
    `// ${HEADER}`,
    'import type { ITheme } from "@xterm/xterm";',
    "",
    'export type Mode = "day" | "night";',
    "",
    "/** All token values per mode, nested by the dots in the token name. Sizes in px. */",
    `export const tokens = {\n  day: ${json(resolvedTree("day"))},\n  night: ${json(resolvedTree("night"))},\n} as const;`,
    "",
    "/** Penpot typographies. Sizes and letter spacing in px. */",
    `export const typography = ${json(typography)} as const;`,
    "",
    "/** xterm.js themes for the light and dark terminal (the per-window switch, not the mode). */",
    `export const xtermTheme = {\n  light: ${json(xtermTheme("light"))},\n  dark: ${json(xtermTheme("dark"))},\n} satisfies Record<"light" | "dark", ITheme>;`,
    "",
  ].join("\n");
}

// ---------- tokens.html

const esc = (s) =>
  String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
const tsPath = (name) =>
  "tokens[mode]" +
  name
    .split(".")
    .map((p) =>
      /^[a-z_$][\w$]*$/i.test(p)
        ? `.${p}`
        : `[${/^\d+$/.test(p) ? p : JSON.stringify(p)}]`,
    )
    .join("");

const SECTIONS = [
  ["Palette", (n) => n.startsWith("palette.")],
  ["Spacing scale", (n) => /^space\.\d/.test(n)],
  ["Size scale", (n) => /^size\.\d/.test(n)],
  ["Radius scale", (n) => n.startsWith("radius.")],
  ["Opacity scale", (n) => /^opacity\.\d/.test(n)],
  [
    "Interface colours",
    (n) =>
      n.startsWith("color.") &&
      !/^color\.(status|agent|art|xterm|scene|wood|light|tag|packet)\./.test(n),
  ],
  ["Status colours", (n) => n.startsWith("color.status.")],
  ["Agent colours", (n) => n.startsWith("color.agent.")],
  ["Terminal palettes", (n) => n.startsWith("color.xterm.")],
  ["Logo", (n) => n.startsWith("color.art.logo.")],
  ["2D plant icons", (n) => /^color\.art\.(plant|pot)\./.test(n)],
  [
    "Component sizes and spacing",
    (n) => /^(space|size)\./.test(n) && !/^(space|size)\.\d/.test(n),
  ],
  ["Borders", (n) => n.startsWith("border.")],
  ["Shadows", (n) => n.startsWith("shadow.")],
  [
    "Opacity",
    (n) =>
      n.startsWith("opacity.") &&
      !/^opacity\.\d/.test(n) &&
      !n.startsWith("opacity.scene"),
  ],
  ["Fonts", (n) => n.startsWith("font.")],
  [
    "3D scene: colours",
    (n) => /^color\.(scene|wood|light|tag|packet)\./.test(n),
  ],
  [
    "3D scene: numbers",
    (n) => n.startsWith("scene.") || n.startsWith("opacity.scene"),
  ],
];

// Tailwind utility shown in the table: the namespace's prefix, or * where several apply (bg-, text-, p-, w- …).
const TW_PREFIX = { radius: "rounded", shadow: "shadow", font: "font" };
const twUtility = (tw) => `${TW_PREFIX[tw.ns] ?? "*"}-${tw.tail}`;

function preview(name, type, inScene) {
  const v = inScene ? "" : `var(${cssVar(name)})`;
  if (type === "color")
    return inScene ? null : `<span class="sw" style="background:${v}"></span>`;
  if (type === "shadow")
    return `<span class="shadow" style="box-shadow:${v}"></span>`;
  if (type === "spacing" || type === "sizing")
    return `<span class="bar" style="width:min(${v},160px)"></span>`;
  if (type === "borderRadius")
    return `<span class="rad" style="border-radius:${v}"></span>`;
  if (type === "fontFamilies")
    return `<span style="font-family:${v};font-size:18px">gitspore 0:43</span>`;
  return null;
}

function buildHtml(css) {
  const day = fullEnv("day");
  const night = fullEnv("night");
  const sceneNames = new Set([
    ...sceneSets.shared.keys(),
    ...sceneSets.day.keys(),
  ]);
  const shown = (env, n) => {
    const t = resolve(env, n);
    const v = tsValue(n, t);
    if (typeof v !== "number" || !PX_TYPES.has(t.type)) return String(v);
    return inRem(n, t.type) ? `${v}px · ${rem(v)}` : `${v}px`;
  };
  const swatchFor = (env, n) =>
    env.get(n).type === "color"
      ? `<span class="sw" style="background:${esc(shown(env, n))}"></span>`
      : "";
  const copy = (text) =>
    `<button class="copy" data-copy="${esc(text)}" title="Copy">${esc(text)}</button>`;

  const sections = SECTIONS.map(([title, test]) => {
    const names = [...day.keys()].filter(test);
    if (!names.length) return "";
    const rows = names.map((n) => {
      const token = day.get(n);
      const inScene = sceneNames.has(n);
      const dv = shown(day, n);
      const nv = shown(night, n);
      const ref = refOf(token.value);
      const tw = inScene ? null : twName(n);
      const pv = preview(n, token.type, inScene);
      return `<tr>
<td><code>${esc(n)}</code>${ref ? `<div class="ref">→ ${esc(ref)}</div>` : ""}</td>
<td class="pv">${pv ?? (token.type === "color" ? swatchFor(day, n) : "")}</td>
<td>${swatchFor(day, n)}<code>${esc(dv)}</code></td>
<td>${nv !== dv ? `${swatchFor(night, n)}<code>${esc(nv)}</code>` : '<span class="same">same</span>'}</td>
<td>${inScene ? '<span class="same">TS only</span>' : copy(`var(${cssVar(n)})`)}</td>
<td>${tw ? copy(twUtility(tw)) : '<span class="same">–</span>'}</td>
<td>${copy(tsPath(n))}</td>
</tr>`;
    });
    const id = title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    return `<section id="${id}"><h2>${esc(title)} <small>${names.length}</small></h2>
<table><thead><tr><th>Token</th><th></th><th>Day</th><th>Night</th><th>CSS</th><th>Tailwind</th><th>TS</th></tr></thead>
<tbody>${rows.join("\n")}</tbody></table></section>`;
  });

  const typoRows = typographies.map(
    (t) => `<tr><td><code>${t.group}/${t.key}</code></td>
<td class="pv"><span style="font:var(--type-${t.id});letter-spacing:var(--text-${t.id}--letter-spacing);text-transform:${t.textTransform}">#15 avatar-upload 0:43</span></td>
<td><code>${t.fontSize}px (${typeSize(t)}) / ${t.fontWeight} / ${t.lineHeight}</code></td>
<td>${copy(`font: var(--type-${t.id})`)}</td><td>${copy(`text-${t.id} font-${t.family.split(".").at(-1)}`)}</td>
<td>${copy(`typography.${t.group}${/^[a-z]\w*$/i.test(t.key) ? `.${t.key}` : `["${t.key}"]`}`)}</td></tr>`,
  );

  const ansi = (pal) => {
    const th = xtermTheme(pal);
    const cells = ANSI.flatMap((c) => [
      c,
      `bright${c[0].toUpperCase()}${c.slice(1)}`,
    ]).map((k) => `<span style="color:${th[k]}">${k}</span>`);
    return `<div class="ansi" style="background:${th.background};color:${th.foreground}"><b>${pal}</b> ${cells.join(" ")}
<span style="background:${th.selectionBackground}">selection</span> <span style="background:${th.cursor};color:${th.cursorAccent}">▌</span></div>`;
  };

  const snippet = (title, lang, code) =>
    `<details><summary>${esc(title)}</summary><pre><code class="${lang}">${esc(code.trim())}</code></pre></details>`;

  return `<!doctype html>
<!-- ${HEADER} -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>gitspore tokens</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800&family=Fredoka:wght@600&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
<style>
${css}
body { margin: 0; background: var(--color-panel-2); color: var(--color-ink); font: 500 15px/1.4 var(--font-ui); }
header { position: sticky; top: 0; z-index: 2; display: flex; gap: 16px; align-items: center; padding: 12px 24px; background: var(--color-panel); box-shadow: var(--shadow-lg); }
header h1 { margin: 0; font: var(--type-title-panel); font-size: 24px; }
header nav { display: flex; flex-wrap: wrap; gap: 4px 12px; font-size: 13px; flex: 1; }
header a { color: var(--color-muted); }
main { padding: 16px 24px 64px; max-width: 1400px; }
section, .intro { background: var(--color-panel); border-radius: var(--radius-xl); padding: 16px; margin: 16px 0; overflow-x: auto; }
h2 { font: var(--type-title-notification); margin: 0 0 8px; } h2 small { font: 500 14px var(--font-ui); color: var(--color-muted); }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th { text-align: left; color: var(--color-muted); font-weight: 600; padding: 4px 8px; }
td { padding: 4px 8px; border-top: 1px solid var(--color-hover); vertical-align: middle; white-space: nowrap; }
tr:nth-child(odd) td { background: var(--color-hover); }
code, .copy { font: 400 12.5px var(--font-mono); }
.copy { border: 0; background: none; color: var(--color-ink); cursor: copy; padding: 2px 4px; border-radius: 4px; }
.copy:hover { background: var(--color-hover); } .copy.done { background: var(--color-accent); color: var(--color-accent-ink); }
.ref, .same { color: var(--color-muted); font-size: 12px; }
.sw { display: inline-block; width: 18px; height: 18px; border-radius: 4px; vertical-align: middle; margin-right: 6px; box-shadow: inset 0 0 0 1px rgba(0,0,0,.15); }
.pv .sw { width: 36px; height: 22px; }
.bar { display: inline-block; height: 10px; background: var(--color-accent); border-radius: 2px; vertical-align: middle; }
.rad { display: inline-block; width: 36px; height: 24px; background: var(--color-plate); }
.shadow { display: inline-block; width: 48px; height: 24px; background: var(--color-panel); border-radius: 6px; margin: 8px; }
.ansi { font: 400 13px/1.6 var(--font-mono); padding: 10px 12px; border-radius: 8px; margin: 6px 0; }
details { margin: 6px 0; } summary { cursor: pointer; font-weight: 600; }
pre { background: var(--color-terminal-bg); color: var(--color-terminal-fg); padding: 12px; border-radius: 8px; overflow-x: auto; }
.toggle { border: 0; border-radius: var(--radius-lg); background: var(--color-accent); color: var(--color-accent-ink); font: var(--type-ui-button); padding: 8px 14px; cursor: pointer; }
:focus-visible { outline: var(--border-focus) solid var(--color-focus); outline-offset: var(--space-focus-offset); }
</style>
</head>
<body>
<header><h1>gitspore tokens</h1>
<nav>${SECTIONS.map(([t]) => `<a href="#${t.toLowerCase().replace(/[^a-z0-9]+/g, "-")}">${esc(t)}</a>`).join("")}<a href="#typography">Typography</a></nav>
<button class="toggle" id="mode">Night</button></header>
<main>
<div class="intro">
<p>Every design value of gitspore. Penpot (<code>gitspore_v01</code>) is the source; <code>apps/web/src/theme/tokens.json</code> is its copy, <code>scene.json</code> holds the 3D values. Change a value in Penpot, dump it, run <code>npm run tokens</code>. Click any value to copy it.</p>
<p>Three layers. <b>Base</b> (<code>cozy-06/base</code>) holds the only raw interface values: palette, spacing, size, radius and opacity scales; <code>space.N</code> and <code>size.N</code> are N × 4 px. <b>Semantic</b> tokens (<code>color.ink</code>, <code>color.panel</code> …) point into base; day and night differ only in which base token they point to. <b>Component</b> tokens exist only where code or a layout rule needs a handle (<code>size.row</code>, <code>size.panel-width</code>, <code>space.layout.edge</code>). Content colours (<code>color.agent.*</code>, <code>color.art.*</code>, <code>color.xterm.*</code>) hold their own values. CSS uses rem for spacing, sizes, radii and font sizes (1rem = 16px), px for borders, shadows and everything terminal; <code>tokens.ts</code> has px numbers.</p>
<p>Tailwind classes exist for semantic colours, kept component handles (<code>h-row</code>, <code>w-panel-width</code>, <code>gap-layout-edge</code>), base radii (<code>rounded-lg</code>, same names and values as Tailwind's), shadows, fonts and typographies, plus <code>bg-terminal-bg</code> and <code>text-terminal-fg</code>. Base spacing, sizes, opacity and the palette have none: Tailwind's own <code>p-4</code>, <code>w-10</code>, <code>opacity-35</code> are the same values. Content colours have none either; use the CSS variable or <code>tokens</code>. In the Tailwind column <code>*-row</code> means <code>h-row</code>, <code>w-…</code>, <code>bg-…</code> and so on. <code>color.muted</code> and <code>color.accent</code> have no utility because shadcn uses those names: use <code>text-muted-foreground</code> and <code>bg-primary</code>.</p>
${snippet(
  "CSS / CSS modules",
  "css",
  `
.panel {
  background: var(--color-panel);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-lg);
  padding: var(--space-2);
}
.title { font: var(--type-title-panel); }`,
)}
${snippet(
  "Tailwind",
  "html",
  `
<div className="bg-panel rounded-xl shadow-lg p-2">
  <h2 className="text-title-panel font-title">Your pots</h2>
  <button className="h-10 px-4 gap-2 rounded-lg bg-primary text-primary-foreground">Open</button>
</div>`,
)}
${snippet(
  "React Three Fiber",
  "ts",
  `
import { tokens } from "@/theme/tokens";
const t = tokens[mode]; // "day" | "night"
<meshStandardMaterial color={t.color.status.waiting} emissiveIntensity={t.scene.glow} />`,
)}
${snippet(
  "xterm.js",
  "ts",
  `
import { xtermTheme, typography } from "@/theme/tokens";
const term = new Terminal({
  theme: xtermTheme[windowTerminal], // "light" | "dark", the per-window switch
  fontFamily: typography.mono.terminal.fontFamily,
  fontSize: typography.mono.terminal.fontSize,
  lineHeight: typography.mono.terminal.lineHeight,
});`,
)}
${snippet(
  "Mode and per-window terminal",
  "html",
  `
<html class="dark">  <!-- night, set by next-themes; no class = follow the system -->
<div class="terminal-light"> <!-- this window's terminal stays light -->`,
)}
</div>
${sections.join("\n")}
<section id="typography"><h2>Typography <small>${typographies.length}</small></h2>
<table><thead><tr><th>Penpot</th><th></th><th>Size / weight / line height</th><th>CSS</th><th>Tailwind</th><th>TS</th></tr></thead>
<tbody>${typoRows.join("\n")}</tbody></table></section>
<section id="xterm"><h2>xterm themes</h2>${ansi("light")}${ansi("dark")}</section>
</main>
<script>
const root = document.documentElement, btn = document.getElementById("mode");
const dark = () => root.classList.contains("dark") || (!root.classList.contains("light") && matchMedia("(prefers-color-scheme: dark)").matches);
const label = () => { btn.textContent = dark() ? "Day" : "Night"; };
btn.onclick = () => { const night = !dark(); root.classList.toggle("dark", night); root.classList.toggle("light", !night); label(); };
label();
document.addEventListener("click", (e) => {
  const b = e.target.closest(".copy"); if (!b) return;
  navigator.clipboard.writeText(b.dataset.copy).then(() => { b.classList.add("done"); setTimeout(() => b.classList.remove("done"), 700); });
});
</script>
</body>
</html>
`;
}

// ---------- write or check

async function format(file, source) {
  if (file.endsWith(".html")) return source; // design-docs/ is not formatted by Prettier
  const options = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(source, { ...options, filepath: file });
}

const css = buildCss();
const outputs = [
  [path.join(themeDir, "tokens.css"), css],
  [path.join(themeDir, "tailwind.css"), buildTailwind()],
  [path.join(themeDir, "tokens.ts"), buildTs()],
  [path.join(repoRoot, "design-docs/design/tokens.html"), buildHtml(css)],
];

let stale = 0;
for (const [file, source] of outputs) {
  const content = await format(file, source);
  const rel = path.relative(repoRoot, file);
  if (check) {
    const current = await readFile(file, "utf8").catch(() => null);
    if (current !== content) {
      stale++;
      console.error(`stale: ${rel}`);
    }
  } else {
    await writeFile(file, content);
    console.log(`wrote ${rel}`);
  }
}
if (stale) {
  console.error("Run `npm run tokens` and commit the result.");
  process.exit(1);
}
